### ISSUE TITLE
Manual Fuel Placement

### ISSUE THREAD

**Issue by GP2P** [GP2P/FarmSimulator-RL#11]

**Comment by kaseyleee** [comment]
With commit fdde25f2df1e25322df75bb8da0b191f40e51dc5 user can now drop fuel in game.  We currently do not support configuring fuel locations at the beginning of the game

**Comment by kaseyleee** [comment]
With commit fdde25f2df1e25322df75bb8da0b191f40e51dc5 user can now drop fuel in game.  We currently do not support configuring fuel locations at the beginning of the game
