### ISSUE TITLE
Make rooms configurable

### ISSUE THREAD

**Issue by GP2P** [GP2P/FarmSimulator-RL#18]
- [x] Expose room variable for editing in sidebar
- [x] Set 2 points for two corners of the rooms

**Comment by kaseyleee** [comment]
- [ ]     Expose room variable for editing in sidebar
- [ ]     Set 2 points for two corners of the rooms

**Comment by GP2P** [comment]
6dfecad271831c4fd03fe4555ce4051b1c52d10a and 04613ca0ed99899834c233e7e3287b994e002048
