### ISSUE TITLE
Ability to have multiple rooms [optional]

### ISSUE THREAD

**Issue by GP2P** [GP2P/FarmSimulator-RL#19]
- [x] Choose different amounts of gates per ~room~ side of each room

**Comment by kaseyleee** [comment]
- [ ] Choose different amounts of gates per room

**Comment by GP2P** [comment]
We made it feasible by using an array of pairs of coords in the SaveGame default values list in 4112e0e

**Comment by GP2P** [comment]
Changed to a roon config struct and can be customized in the SaveGame like so:

![Image](https://github.com/GP2P/FarmSimulator-RL/assets/73323107/21ce3c46-40b1-4bf1-9f56-4e6b57ef7083)
